# Generated by Django 4.1.6 on 2023-02-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
    ]
